# -*- coding: utf-8 -*-
"""ML Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-T5Ysx2VRnFWSxjTQkLZAksMzv46W4X
"""

# pip install Flask

# # An object of Flask class is our WSGI application.
# from flask import Flask

# # Flask constructor takes the name of
# # current module (__name__) as argument.
# app = Flask(__name__)

# # The route() function of the Flask class is a decorator,
# # which tells the application which URL should call
# # the associated function.
# @app.route('/')
# # ‘/’ URL is bound with hello_world() function.
# def hello_world():
#     return 'Hello World'

# # main driver function
# if __name__ == '__main__':

#     # run() method of Flask class runs the application
#     # on the local development server.
#     app.run()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns